# Generated by Django 5.2.1 on 2025-05-14 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('direccion', models.TextField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.cargo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aniomes', models.DateField()),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horas_extra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bono', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iess', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('tot_ing', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('tot_des', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('neto', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.tipocontrato'),
        ),
    ]
