# Generated by Django 5.2 on 2025-05-14 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0002_cargo_departamento_empleado_rol_tipocontrato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('frecuencia_dias', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_permiso', models.DateField()),
                ('dias', models.PositiveIntegerField(blank=True, null=True)),
                ('horas', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.empleado')),
                ('tipo_permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.tipopermiso')),
            ],
        ),
    ]
